puts "The students of Villains Academy"
puts "------------"
puts "Dr.Hanibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Coleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the west"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"

print "Overall, we have "
print 11
puts "great students"
